# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34142f780248efda0a24896add767dd57df4b84c0ce74d5023cfab65a7b347091e2ddf48289d30033f0635312a4bdad6f61de718654baee381290cdc0ac49acc

test:
  secret_key_base: 6380773f63c7110456f4fe395cc2c1e8f3c1eda6895550a790abdaa1cb773efbd7e698413bb26ba1798ae32d5be747a3e30d4429f95247dd2e34fa8a4839bd2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
